server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3308/identity_service"
    username: root
    password: root
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      log-condition-evaluation-delta: false

jwt:
  signerKey: "SLHLfWZMSj23g64t76GxuyaJAJskUCeyrMLSRDyM6bghzKGp5Pp9m0KloQD3riWU"
  valid-duration: 3600 # 1 hour in second
  refreshable-duration: 360000 # 100 hours in second